openapi: 3.0.3
info:
  title: 관리자 REST API 명세 ( yaml )
  description: 관리자 REST API 명세 with Swagger ( yaml )
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Generated server url
security:
  - Authorization: []
paths:
  /api/mng/user/list:
    get:
      tags:
        - 관리자 회원 컨트롤러
      summary: 회원 목록
      description: 회원 목록 조회
      operationId: userList
      parameters:
        - name: userVO
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/사용자 DTO'

      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
              examples:
                test:
                  value:
                    searchKeyword: "2222"
                    pageIndex: "1"
                guide:
                  value:
                    searchKeyword: "회원 PWD"
                    pageIndex: "회원 순번"
  /api/mng/user/proc:
    put:
      tags:
        - 관리자 회원 컨트롤러
      summary: 회원 수정
      description: 회원 수정
      operationId: userUpdateProc
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/사용자 DTO'
            examples:
              test:
                value:
                  user_seq: "5"
                  user_pwd: "2222"
                  user_auth: "ROLE_USER"
                  user_name: "테스트"
                  user_email: "test@test.com"
              guide:
                value:
                  user_seq: "회원 순번"
                  user_pwd: "회원 PWD"
                  user_auth: "회원 권한"
                  user_name: "회원 이름"
                  user_email: "회원 이메일"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
    post:
      tags:
        - 관리자 회원 컨트롤러
      summary: 회원 등록
      description: 회원 등록
      operationId: userSetProc
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/사용자 DTO'
            examples:
              test:
                value:
                  user_id: "test_mng001"
                  user_pwd: "2222"
                  user_auth: "ROLE_USER"
                  user_name: "테스트"
                  user_email: "test@test.com"
              guide:
                value:
                  user_id: "회원 ID"
                  user_pwd: "회원 PWD"
                  user_auth: "회원 권한"
                  user_name: "회원 이름"
                  user_email: "회원 이메일"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
    delete:
      tags:
        - 관리자 회원 컨트롤러
      summary: 회원 탈퇴 및 복구
      description: out_yn 값으로 회원 탈퇴 및 복구
      operationId: userDeleteProc
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/사용자 DTO'
            examples:
              test:
                value:
                  user_seq: "24"
                  flag: "d"
                  out_yn: "Y"
              guide:
                value:
                  user_seq: "회원 순번"
                  flag: "플래그 (d) 이미 탈퇴면 복구"
                  out_yn: "탈퇴 여부 (Y or N)"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/user/check:
    post:
      tags:
        - 관리자 회원 컨트롤러
      summary: 회원 ID 중복 체크
      description: 회원 아이디 중복체크
      operationId: getUserCheck
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/사용자 DTO'
            examples:
              test:
                value:
                  user_id: "test_mng001"
              guide:
                value:
                  user_id: "회원 ID"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /mng/bbs/proc:
    put:
      tags:
        - bbs-mng-controller
      summary: 게시판 수정
      operationId: updateBbs
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/BbsMngVO'
            example:

        required: true
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: string
    post:
      tags:
        - bbs-mng-controller
      summary: 게시판 등록
      operationId: createBbs
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/BbsMngVO'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: string
    delete:
      tags:
        - bbs-mng-controller
      summary: 게시판 삭제
      operationId: deleteBbs
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/BbsMngVO'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: string
  /mng/bbs/code/check:
    post:
      tags:
        - bbs-mng-controller
      summary: 게시판 코드 중복검사
      operationId: checkBbsCode
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/BbsMngVO'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: boolean
  /mng/{bbs_seq}/config/bbs/cnt:
    get:
      tags:
        - bbs-mng-controller
      summary: 게시판 존재여부 확인
      operationId: menuLinkList
      parameters:
        - name: bbs_seq
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: string
  /mng/bbs/list:
    get:
      tags:
        - bbs-mng-controller
      summary: 게시판 리스트
      operationId: bbsList
      parameters:
        - name: bbsMngVO
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/BbsMngVO'
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: string
  /mng/bbs/info:
    get:
      tags:
        - bbs-mng-controller
      summary: 게시판 상세정보
      operationId: bbsForm
      parameters:
        - name: bbsMngVO
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/BbsMngVO'
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: string





  /mng/user/check:
    get:
      tags:
        - user-mng-controller
      operationId: getUserCheck_1
      parameters:
        - name: userVO
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/사용자 DTO'
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: boolean
    put:
      tags:
        - user-mng-controller
      operationId: getUserCheck_4
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/사용자 DTO'
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: boolean
    post:
      tags:
        - user-mng-controller
      operationId: getUserCheck_3
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/사용자 DTO'
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: boolean
    delete:
      tags:
        - user-mng-controller
      operationId: getUserCheck_6
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/사용자 DTO'
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: boolean
    options:
      tags:
        - user-mng-controller
      operationId: getUserCheck_7
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/사용자 DTO'
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: boolean
    head:
      tags:
        - user-mng-controller
      operationId: getUserCheck_2
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/사용자 DTO'
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: boolean
    patch:
      tags:
        - user-mng-controller
      operationId: getUserCheck_5
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/사용자 DTO'
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: boolean
  /api/mng/html/proc:
    put:
      tags:
        - Html 관리 컨트롤러
      summary: Html 수정
      operationId: htmlUpdateProc
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/HtmlMngVO'
            examples:
              test:
                value:
                  html_seq : "1"
                  html_title: "html subject1"
                  html_content: "html content1"
              guide:
                value:
                  html_seq : "html 순번"
                  html_title: "제목"
                  html_content: "내용"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
    post:
      tags:
        - Html 관리 컨트롤러
      summary: Html 등록
      operationId: htmlProc
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/HtmlMngVO'
            examples:
              test:
                value:
                  html_title: "html subject1"
                  html_content: "html content1"
              guide:
                value:
                  html_title: "제목"
                  html_content: "내용"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
    delete:
      tags:
        - Html 관리 컨트롤러
      summary: Html 삭제
      operationId: htmlDeleteProc
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/HtmlMngVO'
            examples:
              test:
                value:
                  html_seq: "1"
              guide:
                value:
                  html_seq: "html 순번"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/html/list:
    get:
      tags:
        - Html 관리 컨트롤러
      summary: Html list 조회
      operationId: htmlList
      parameters:
        - name: htmlMngVO
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/HtmlMngVO'
          examples:
            test:
              value:
                pageIndex : "1"
                html_title: "html subject1"
            guide:
              value:
                pageIndex : "페이지 번호"
                html_title: "제목"
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/html/detail/{html_seq}:
    get:
      tags:
        - Html 관리 컨트롤러
      summary: Html 상세보기
      operationId: htmlDetail
      parameters:
        - name: htmlMngVO
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/HtmlMngVO'
        - name: html_seq
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/html/check/{html_seq}:
    get:
      tags:
        - Html 관리 컨트롤러
      summary: Html 존재여부 확인
      description: 메뉴 관리에서 html_seq 로 html 존재여부 확인
      operationId: menuLinkList_1
      parameters:
        - name: html_seq
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/popup/proc:
    put:
      tags:
        - 팝업 관리 컨트롤러
      summary: 팝업 수정
      operationId: popupUpdateProc
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  description: "파일 배열"
                  type: array
                  items:
                    type: string
                    format: binary
                del_file_seq:
                  description: "삭제할 파일 순번(seq)"
                  type: array
                  items:
                    type: string
                popup_seq:
                  description: "팝업 순번"
                  default: "1"
                  type: string
                popup_title:
                  description: "팝업 제목"
                  default: "제목"
                  type: string
                popup_type:
                  description: "팝업 타입 (이미지 : I , HTML : H)"
                  default: "I"
                  type: string
                popup_order:
                  description: "팝업 순서"
                  default: "1"
                  type: string
                content:
                  description: "팝업 내용 (HTML)"
                  default: "팝업 html 내용"
                  type: string
                link_type:
                  description: "링크 타입 (현재창 : N , 새창 : B)"
                  default: "N"
                  type: string
                link_url:
                  description: "링크 URL"
                  default: "http://localhost:8080"
                  type: string
                remark:
                  description: "메모"
                  default: "팝업 메모"
                  type: string
                del_yn:
                  description: "삭제여부 (Y, N)"
                  default: "N"
                  type: string
                use_yn:
                  description: "사용 여부 (Y, N)"
                  default: "Y"
                  type: string
                popup_start_date:
                  description: "게시 시작일"
                  default: "2024-01-01 00:00:00"
                  type: string
                popup_end_date:
                  description: "게시 종료일"
                  default: "2024-12-31 00:00:00"
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
    post:
      tags:
        - 팝업 관리 컨트롤러
      summary: 팝업 등록
      operationId: popupInsertProc
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  description: "파일 배열"
                  type: array
                  items:
                    type: string
                    format: binary
                popup_title:
                  description: "팝업 제목"
                  default: "제목"
                  type: string
                popup_type:
                  description: "팝업 타입 (이미지 : I , HTML : H)"
                  default: "I"
                  type: string
                popup_order:
                  description: "팝업 순서"
                  default: "1"
                  type: string
                content:
                  description: "팝업 내용 (HTML)"
                  default: "팝업 html 내용"
                  type: string
                link_type:
                  description: "링크 타입 (현재창 : N , 새창 : B)"
                  default: "N"
                  type: string
                link_url:
                  description: "링크 URL"
                  default: "http://localhost:8080"
                  type: string
                remark:
                  description: "메모"
                  default: "팝업 메모"
                  type: string
                del_yn:
                  description: "삭제여부 (Y, N)"
                  default: "N"
                  type: string
                use_yn:
                  description: "사용 여부 (Y, N)"
                  default: "Y"
                  type: string
                popup_start_date:
                  description: "게시 시작일"
                  default: "2024-01-01 00:00:00"
                  type: string
                popup_end_date:
                  description: "게시 종료일"
                  default: "2024-12-31 00:00:00"
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
    delete:
      tags:
        - 팝업 관리 컨트롤러
      summary: 팝업 삭제
      operationId: popupDeleteProc
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/PopupMngVO'
            examples:
              test:
                value:
                  popup_seq: "1"
              guide:
                value:
                  popup_seq: "팝업 순번"
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/popup/list:
    get:
      tags:
        - 팝업 관리 컨트롤러
      summary: 팝업 리스트
      operationId: popupList
      parameters:
        - name: popupMngVO
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/PopupMngVO'
          examples:
            test:
              value:
                pageIndex: "1"
                searchKeyword: "팝업1"
            guide:
              value:
                pageIndex: "팝업 순번"
                searchKeyword: "검색 키워드 (제목)"
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/popup/detail/{popup_seq}:
    get:
      tags:
        - 팝업 관리 컨트롤러
      summary: 팝업 상세정보
      operationId: popupDetail
      parameters:
        - name: popup_seq
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'

  /api/mng/banner/proc:
    put:
      tags:
        - 배너 관리 컨트롤러
      summary: 배너 수정
      operationId: bannerUpdateProc
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  description: "파일 배열"
                  type: array
                  items:
                    type: string
                    format: binary
                del_file_seq:
                  description: "삭제할 파일 순번(seq)"
                  type: array
                  items:
                    type: string
                banner_seq:
                  description: "배너 순번(seq)"
                  default: "1"
                  type: string
                banner_title:
                  description: "배너 제목"
                  default: "배너 1"
                  type: string
                banner_alt:
                  description: "배너 설명"
                  default: "배너 설명1"
                  type: string
                link_type:
                  description: "링크타입 (새창 : _blank, 현재창 : _self, 사용안함 : null )"
                  default: "_self"
                  type: string
                link_url:
                  description: "배너 링크 URL"
                  default: "https://www.naver.com"
                  type: string
                banner_order:
                  description: "배너 순서"
                  default: "1"
                  type: string
                remark:
                  description: "메모"
                  default: "배너 메모"
                  type: string
                use_yn:
                  description: "사용여부 (Y, N)"
                  default: "Y"
                  type: string
                del_yn:
                  description: "삭제여부 (Y, N)"
                  default: "N"
                  type: string
                banner_start_date:
                  description: "'게시 시작일'"
                  default: "2024-01-01 00:00:00"
                  type: string
                banner_end_date:
                  description: "게시 종료일"
                  default: "2024-12-31 00:00:00"
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
    post:
      tags:
        - 배너 관리 컨트롤러
      summary: 배너 등록
      operationId: bannerInsertProc
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  description: "파일 배열"
                  type: array
                  items:
                    type: string
                    format: binary
                banner_title:
                  description: "배너 제목"
                  default: "배너 1"
                  type: string
                banner_alt:
                  description: "배너 설명"
                  default: "배너 설명1"
                  type: string
                link_type:
                  description: "링크타입 (새창 : _blank, 현재창 : _self, 사용안함 : null )"
                  default: "_self"
                  type: string
                link_url:
                  description: "배너 링크 URL"
                  default: "https://www.naver.com"
                  type: string
                banner_order:
                  description: "배너 순서"
                  default: "1"
                  type: string
                remark:
                  description: "메모"
                  default: "배너 메모"
                  type: string
                use_yn:
                  description: "사용여부 (Y, N)"
                  default: "Y"
                  type: string
                del_yn:
                  description: "삭제여부 (Y, N)"
                  default: "N"
                  type: string
                banner_start_date:
                  description: "'게시 시작일'"
                  default: "2024-01-01 00:00:00"
                  type: string
                banner_end_date:
                  description: "게시 종료일"
                  default: "2024-12-31 00:00:00"
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
    delete:
      tags:
        - 배너 관리 컨트롤러
      summary: 배너 삭제
      operationId: bannerDeleteProc
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/BannerMngVO'
            examples:
              test:
                value:
                  banner_seq: "1"
              guide:
                value:
                  banner_seq: "배너 순번"
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/banner/list:
    get:
      tags:
        - 배너 관리 컨트롤러
      summary: 배너 목록
      operationId: bannerList
      parameters:
        - name: bannerMngVO
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/BannerMngVO'
          examples:
            test:
              value:
                pageIndex: "1"
                searchKeyword : "배너"
            guide:
              value:
                pageIndex: "페이지 index"
                searchKeyword: "검색어 (제목)"
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/banner/detail/{banner_seq}:
    get:
      tags:
        - 배너 관리 컨트롤러
      summary: 배너 상세정보
      operationId: bannerDetail_1
      parameters:
        - name: banner_seq
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/adminAccess/proc:
    put:
      tags:
        - 관리자 페이지 접근 IP 관리 컨트롤러
      summary: 관리자 페이지 접근 가능 IP 수정
      operationId: updateProc
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/AdminAccessMngVO'
            examples:
              test:
                value:
                  admin_access_seq: "2"
                  admin_access_nm: "관리자 수정"
                  admin_access_ip: "127.0.0.1"
                  use_yn: "Y"
                  del_yn: "N"
              guide:
                value:
                  admin_access_seq: "접근 가능 IP 순번(seq)"
                  admin_access_nm: "접근 가능 이름"
                  admin_access_ip: "접근 가능 IP"
                  use_yn: "사용여부 (Y , N)"
                  del_yn: "삭제여부 (Y , N)"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
    post:
      tags:
        - 관리자 페이지 접근 IP 관리 컨트롤러
      summary: 관리자 페이지 접근 가능 IP 등록
      operationId: insertProc
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/AdminAccessMngVO'
            examples:
              test:
                value:
                  admin_access_nm: "관리자"
                  admin_access_ip: "127.0.0.1"
                  use_yn: "Y"
                  del_yn: "N"
              guide:
                value:
                  admin_access_nm: "접근 가능 이름"
                  admin_access_ip: "접근 가능 IP"
                  use_yn: "사용여부 (Y , N)"
                  del_yn: "삭제여부 (Y , N)"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
    delete:
      tags:
        - 관리자 페이지 접근 IP 관리 컨트롤러
      summary: 관리자 페이지 접근 가능 IP 삭제
      operationId: deleteProc
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/AdminAccessMngVO'
            examples:
              test:
                value:
                  admin_access_seq: "2"
              guide:
                value:
                  admin_access_seq: "접근 가능 IP 순번(seq)"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/adminAccess/list:
    get:
      tags:
        - 관리자 페이지 접근 IP 관리 컨트롤러
      summary: 관리자 페이지 접근 가능 IP 리스트
      operationId: list
      parameters:
        - name: adminAccessMngVO
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/AdminAccessMngVO'
          examples:
            test:
              value:
                pageIndex: "1"
                searchKeyword: "127.0.0.1"
            guide:
              value:
                pageIndex: "페이지 번호"
                searchKeyword: "검색 키워드 ( ip )"
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/adminAccess/detail/{admin_access_seq}:
    get:
      tags:
        - 관리자 페이지 접근 IP 관리 컨트롤러
      summary: 관리자 페이지 접근 가능 IP 상세정보
      operationId: detail
      parameters:
        - name: admin_access_seq
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/code/proc:
    put:
      tags:
        - 코드 관리 컨트롤러
      summary: 코드 수정
      operationId: codeUpdate
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/CodeMngVO'
            examples:
              test:
                value:
                  code_seq: '13'
                  code: 'test'
                  code_nm: '테스트 코드'
                  use_yn: 'Y'
                  ord: '1'
                  remark: "테스트 코드"
              guide:
                value:
                  code_seq: '코드 순번'
                  code: '코드'
                  code_nm: '코드 이름'
                  use_yn: '사용여부 (Y ,N)'
                  ord: '정렬 순서'
                  remark: "메모"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
    post:
      tags:
        - 코드 관리 컨트롤러
      summary: 코드 등록
      operationId: codeInsert
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/CodeMngVO'
            examples:
              test:
                value:
                  code : 'test'
                  code_nm : '테스트 코드'
                  prt_seq : '0'
                  use_yn : 'Y'
                  ord : '1'
                  remark : "테스트 코드"
              guide:
                value:
                  code: '코드'
                  code_nm: '코드 이름'
                  prt_seq: '부모 코드 순번'
                  use_yn: '사용여부 (Y ,N)'
                  ord: '정렬 순서'
                  remark: "메모"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
    delete:
      tags:
        - 코드 관리 컨트롤러
      summary: 코드 삭제
      operationId: codeDelete
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/CodeMngVO'
            examples:
              test:
                value:
                  code_seq: '13'
                  flag : 'd'
              guide:
                value:
                  code: '코드 순번'
                  flag: '해당 코드 : d , 코드와 자식코드 전체 : dp '
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/code/list:
    get:
      tags:
        - 코드 관리 컨트롤러
      summary: 코드 리스트
      operationId: codeList
      parameters:
        - name: codeVO
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/CodeMngVO'
          examples:
            test:
              value:
                code: "test"
            guide:
              value:
                code: "코드"
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/code/detail/{code}:
    get:
      tags:
        - 코드 관리 컨트롤러
      summary: 코드 상세정보
      operationId: codeDetailAjax
      parameters:
        - name: code
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/code/check:
    post:
      tags:
        - 코드 관리 컨트롤러
      summary: 코드 중복체크
      operationId: codeCheck
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/CodeMngVO'
            examples:
              test:
                value:
                  code: "test"
              guide:
                value:
                  code: "코드"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/menu/proc:
    put:
      tags:
        - 메뉴 관리 컨트롤러
      summary: 메뉴 정보 수정
      operationId: menuInfoUpdate
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/MenuMngVO'
            examples:
              test:
                value:
                  menu_info_seq : "1"
                  menu_name : "메뉴 수정 1"
                  remark : "메모 수정"
                  use_yn : "Y"
              guide:
                value:
                  menu_info_seq : "메뉴 순번"
                  menu_name: "메뉴 수정 1"
                  remark: "메모 수정"
                  use_yn: "Y"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
    post:
      tags:
        - 메뉴 관리 컨트롤러
      summary: 메뉴 정보 등록
      operationId: menuInfoProc
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/MenuMngVO'
            examples:
              test:
                value:
                  menu_name : "PC 테스트1"
                  remark : "테스트"
                  use_yn : "Y"
                  del_yn : "N"
              guide:
                value:
                  menu_name: "메뉴명"
                  remark: "메모"
                  use_yn: "사용여부 ( Y, N )"
                  del_yn: "삭제여부 ( Y, N )"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
    delete:
      tags:
        - 메뉴 관리 컨트롤러
      summary: 메뉴 정보 삭제
      operationId: menuInfoDelete
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/MenuMngVO'
            examples:
              test:
                value:
                  menu_info_seq : "2"
              guide:
                value:
                  menu_info_seq : "메뉴 정보 순번"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/menu/list:
    get:
      tags:
        - 메뉴 관리 컨트롤러
      summary: 메뉴 정보 목록
      operationId: menuInfoList
      parameters:
        - name: menuMngVO
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/MenuMngVO'
          examples:
            test:
              value:
                pageIndex: "1"
            guide:
              value:
                pageIndex: "페이지 번호"
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/menu/detail/{menu_info_seq}:
    get:
      tags:
        - 메뉴 관리 컨트롤러
      summary: 메뉴 정보 상세
      operationId: menuInfoDetail
      parameters:
        - name: menu_info_seq
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/menu/data/{menu_type}/{menu_info_seq}/list:
    get:
      tags:
        - 메뉴 관리 컨트롤러
      summary: 메뉴 타입별 링크 목록
      operationId: menuLinkList_1
      parameters:
        - name: menu_type
          in: path
          required: true
          schema:
            type: string
          example: "MNT_002 MNT_003 (게시판, html)"
        - name: menu_info_seq
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/menu/data/json:
    get:
      tags:
        - 메뉴 관리 컨트롤러
      summary: 메뉴 데이터 Json
      operationId: menuList
      parameters:
        - name: menu_info_seq
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'
  /api/mng/menu/data/proc:
    post:
      tags:
        - 메뉴 관리 컨트롤러
      summary: 메뉴 데이터 등록
      operationId: setMenu
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/MenuMngVO'
            examples:
              test:
                value:
                  menu_info_seq: "1"
                  menu_json : ""
              guide:
                value:
                  menu_info_seq: "메뉴 정보 순번"
                  menu_json : "[{\"parent\" : \"null\", \"order\":0, \"depth\":0, \"update\":true, \"remark\":\"메뉴1\",\"use_yn\":\"Y\",\"menu_link\":\"#\",\"menu_link_type\":\"LNK_001\",\"menu_type\":\"MNT_004\",\"menu_title\":\"메뉴1\",\"id\":1000001,\"children\":[{\"parent\" : \"1000001\", \"order\":0, \"depth\":1, \"update\":true, \"remark\":\"자식1\",\"use_yn\":\"Y\",\"menu_link\":\"#\",\"menu_link_type\":\"LNK_001\",\"menu_type\":\"MNT_004\",\"menu_title\":\"자식1\",\"id\":1000002}]}]"
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResultVO'

components:
  schemas:
    사용자 DTO:
      type: object
      properties:
        searchCondition:
          type: string
          description: 검색 조건
        searchKeyword:
          type: string
          description: 검색어
        searchUseYn:
          type: string
          description: 검색 사용 여부
          example: Y or N
        searchOrderBy:
          type: string
          description: 검색 정렬 기준
        pageIndex:
          type: integer
          description: 현재 페이지
          format: int32
        pageUnit:
          type: integer
          description: 페이지 개수
          format: int32
        file:
          type: array
          description: 파일 배열
          items:
            type: string
            format: binary
        user_seq:
          type: string
          description: 사용자 시퀀스
        user_id:
          type: string
          description: 사용자 아이디
        user_pwd:
          type: string
          description: 사용자 비밀번호
    BbsMngVO:
      type: object
      properties:
        searchCondition:
          type: string
          description: 검색 조건
        searchKeyword:
          type: string
          description: 검색어
        searchUseYn:
          type: string
          description: 검색 사용 여부
          example: Y or N
        searchOrderBy:
          type: string
          description: 검색 정렬 기준
        pageIndex:
          type: integer
          description: 현재 페이지
          format: int32
        pageUnit:
          type: integer
          description: 페이지 개수
          format: int32
        file:
          type: array
          description: 파일 배열
          items:
            type: string
            format: binary
        user_auth:
          type: string
        read_yn:
          type: string
        write_yn:
          type: string
        update_yn:
          type: string
        delete_yn:
          type: string
        category_nm:
          type: string
        category_del_yn:
          type: string
        category_order:
          type: string
        category_cd:
          type: string
        file_cnt:
          type: string
        bbs_type:
          type: string
        mobile_bbs_type:
          type: string
        bbs_dft_list_cnt:
          type: string
        bbs_page_cnt:
          type: string
        attach_file_use_yn:
          type: string
        comment_use_yn:
          type: string
        reply_use_yn:
          type: string
        notice_use_yn:
          type: string
        secret_use_yn:
          type: string
        category_use_yn:
          type: string
        pwd_use_yn:
          type: string
        date_range_use_yn:
          type: string
        file_size:
          type: string
        file_type:
          type: string
        bbs_info_seq:
          type: string
        bbs_cd:
          type: string
        bbs_nm:
          type: string
        bbs_remark:
          type: string
        bbs_use_yn:
          type: string
        bbs_del_yn:
          type: string
        inpt_seq:
          type: string
        inpt_date:
          type: string
        upd_seq:
          type: string
        upd_date:
          type: string
        date_remark:
          type: string
        bbs_cd_check_yn:
          type: string
        site_type:
          type: string
        data_range_use_yn:
          type: string
    GrantedAuthority:
      type: object
      properties:
        authority:
          type: string
    LoginVO:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        user_id:
          type: string
        user_pwd:
          type: string
        user_email:
          type: string
        pwd_check:
          type: string
        user_auth:
          type: string
        user_status:
          type: string
        out_yn:
          type: string
        user_seq:
          type: string
        last_login_date:
          type: string
        last_login_ip:
          type: string
        inpt_seq:
          type: string
        inpt_date:
          type: string
        upd_seq:
          type: string
        upd_date:
          type: string
        user_name:
          type: string
        user_pwd_req:
          type: string
        token_seq:
          type: string
        access_token:
          type: string
        refresh_token:
          type: string
        enabled:
          type: boolean
        authorities:
          type: array
          items:
            $ref: '#/components/schemas/GrantedAuthority'
        accountNonExpired:
          type: boolean
        credentialsNonExpired:
          type: boolean
        accountNonLocked:
          type: boolean
    ResultVO:
      type: object
      properties:
        resultMsg:
          type: string
          description: 응답 메시지
        resultCode:
          type: integer
          description: 응답 코드
          format: int32
        result:
          type: object
          additionalProperties:
            type: object
            description: 응답 결과 데이터
          description: 응답 결과 데이터
      description: REST API 응답 결과 객체
    FileMngVO:
      type: object
      properties:
        searchCondition:
          type: string
          description: 검색 조건
        searchKeyword:
          type: string
          description: 검색어
        searchUseYn:
          type: string
          description: 검색 사용 여부
          example: Y or N
        searchOrderBy:
          type: string
          description: 검색 정렬 기준
        pageIndex:
          type: integer
          description: 현재 페이지
          format: int32
        pageUnit:
          type: integer
          description: 페이지 개수
          format: int32
        file:
          type: array
          description: 파일 배열
          items:
            type: string
            format: binary
        file_seq:
          type: string
        table_nm:
          type: string
        table_seq:
          type: string
        file_type:
          type: string
        inpt_seq:
          type: string
        inpt_date:
          type: string
        file_flag:
          type: string
        thumbnail_yn:
          type: string
        auth_type:
          type: string
        fileResult:
          type: boolean
    JwtVO:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
    HtmlMngVO:
      type: object
      properties:
        searchCondition:
          type: string
          description: 검색 조건
        searchKeyword:
          type: string
          description: 검색어
        searchUseYn:
          type: string
          description: 검색 사용 여부
          example: Y or N
        searchOrderBy:
          type: string
          description: 검색 정렬 기준
        pageIndex:
          type: integer
          description: 현재 페이지
          format: int32
        pageUnit:
          type: integer
          description: 페이지 개수
          format: int32
        file:
          type: array
          description: 파일 배열
          items:
            type: string
            format: binary
        inpt_user_name:
          type: string
        upd_user_name:
          type: string
        html_seq:
          type: string
        html_title:
          type: string
        html_content:
          type: string
        inpt_seq:
          type: string
        inpt_date:
          type: string
        upd_seq:
          type: string
        upd_date:
          type: string
        del_yn:
          type: string
        flag:
          type: string
    PopupMngVO:
      type: object
      properties:
        searchCondition:
          type: string
          description: 검색 조건
        searchKeyword:
          type: string
          description: 검색어
        searchUseYn:
          type: string
          description: 검색 사용 여부
          example: Y or N
        searchOrderBy:
          type: string
          description: 검색 정렬 기준
        pageIndex:
          type: integer
          description: 현재 페이지
          format: int32
        pageUnit:
          type: integer
          description: 페이지 개수
          format: int32
        file:
          type: array
          description: 파일 배열
          items:
            type: string
            format: binary
        inpt_user_name:
          type: string
        upd_user_name:
          type: string
        popup_seq:
          type: string
        popup_title:
          type: string
        popup_type:
          type: string
        popup_order:
          type: string
        content:
          type: string
        link_type:
          type: string
        link_url:
          type: string
        remark:
          type: string
        del_yn:
          type: string
        use_yn:
          type: string
        inpt_seq:
          type: string
        inpt_date:
          type: string
        upd_seq:
          type: string
        upd_date:
          type: string
        popup_start_date:
          type: string
        popup_end_date:
          type: string
        flag:
          type: string
        file_PATH:
          type: string
        file_SYS_NM:
          type: string
        file_NM:
          type: string
        table_SEQ:
          type: string
    BannerMngVO:
      type: object
      properties:
        searchCondition:
          type: string
          description: 검색 조건
        searchKeyword:
          type: string
          description: 검색어
        searchUseYn:
          type: string
          description: 검색 사용 여부
          example: Y or N
        searchOrderBy:
          type: string
          description: 검색 정렬 기준
        pageIndex:
          type: integer
          description: 현재 페이지
          format: int32
        pageUnit:
          type: integer
          description: 페이지 개수
          format: int32
        file:
          type: array
          description: 파일 배열
          items:
            type: string
            format: binary
        inpt_user_name:
          type: string
        upd_user_name:
          type: string
        banner_seq:
          type: string
        banner_title:
          type: string
        banner_alt:
          type: string
        link_type:
          type: string
        link_url:
          type: string
        banner_order:
          type: string
        remark:
          type: string
        del_yn:
          type: string
        use_yn:
          type: string
        inpt_seq:
          type: string
        inpt_date:
          type: string
        upd_seq:
          type: string
        upd_date:
          type: string
        banner_start_date:
          type: string
        banner_end_date:
          type: string
        banner_type:
          type: string
        banner_title_color:
          type: string
        remark_color:
          type: string
        video_yn:
          type: string
        video_url:
          type: string
        flag:
          type: string
    AdminAccessMngVO:
      type: object
      properties:
        admin_access_seq:
          type: string
        admin_access_nm:
          type: string
        admin_access_ip:
          type: string
        use_yn:
          type: string
        del_yn:
          type: string
        inpt_user_name:
          type: string
        inpt_seq:
          type: string
        inpt_date:
          type: string
        upd_seq:
          type: string
        upd_date:
          type: string
        flag:
          type: string
    CodeMngVO:
      type: object
      properties:
        searchCondition:
          type: string
          description: 검색 조건
        searchKeyword:
          type: string
          description: 검색어
        searchUseYn:
          type: string
          description: 검색 사용 여부
          example: Y or N
        searchOrderBy:
          type: string
          description: 검색 정렬 기준
        pageIndex:
          type: integer
          description: 현재 페이지
          format: int32
        pageUnit:
          type: integer
          description: 페이지 개수
          format: int32
        file:
          type: array
          description: 파일 배열
          items:
            type: string
            format: binary
        code_seq:
          type: string
        code:
          type: string
        code_nm:
          type: string
        prt_seq:
          type: string
        use_yn:
          type: string
        remark:
          type: string
        inpt_seq:
          type: string
        upd_seq:
          type: string
        inpt_date:
          type: string
        ord:
          type: string
        flag:
          type: string
        code_check_yn:
          type: string
        id:
          type: string
        parent:
          type: string
        text:
          type: string
        state:
          type: object
          additionalProperties:
            type: boolean
        code_detail:
          type: string
        code_detail_nm:
          type: string
    MenuMngVO:
      type: object
      properties:
        searchCondition:
          type: string
          description: 검색 조건
        searchKeyword:
          type: string
          description: 검색어
        searchUseYn:
          type: string
          description: 검색 사용 여부
          example: Y or N
        searchOrderBy:
          type: string
          description: 검색 정렬 기준
        pageIndex:
          type: integer
          description: 현재 페이지
          format: int32
        pageUnit:
          type: integer
          description: 페이지 개수
          format: int32
        file:
          type: array
          description: 파일 배열
          items:
            type: string
            format: binary
        access_code:
          type: string
        inpt_date:
          type: string
        inpt_seq:
          type: string
        menu_depth:
          type: string
        menu_info_seq:
          type: string
        menu_json:
          type: string
        menu_link:
          type: string
        menu_link_seq:
          type: string
        menu_link_title:
          type: string
        menu_link_type:
          type: string
        menu_name:
          type: string
        menu_order:
          type: string
        menu_seq:
          type: string
        menu_title:
          type: string
        menu_type:
          type: string
        ord:
          type: string
        prt_seq:
          type: string
        remark:
          type: string
        upd_date:
          type: string
        upd_seq:
          type: string
        show_yn:
          type: string
        highlight_yn:
          type: string
        use_yn:
          type: string
        user_auth:
          type: string
        user_seq:
          type: string
        update_menu:
          type: string
        id:
          type: string
        parent:
          type: string
        depth:
          type: string
        flag:
          type: string
        children:
          type: array
          items:
            $ref: '#/components/schemas/MenuMngVO'
        userVOList:
          type: array
          items:
            $ref: '#/components/schemas/사용자 DTO'
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
